# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXi1JoE3mAQWA3u5l1u6yRnFuTAfJp5V
"""

def identificacaoSistemas(Step, Time, Output, Method='Smith'):
  '''
    Identifies control systems using the Smith or Sundaresan methods based on
    test data, considering a first-order model with transport delay (FOPDT).

    Args:
      - step (float): Amplitude of the input step. Must be a finite, non-zero number.
      - time (array-like): Sampling time points of the process. Must be non-empty.
      - output (array-like): Output samples of the process at the given sampling times. Must be non-empty.
      - method (str): Identification method to be used: 'Smith' (default) or 'Sundaresan'. Must be a valid string.

    Returns:
      - dict: Structure containing the identified system parameters.
  '''